#create_setup.sql script to create db, tables 

CREATE DATABASE CARS;
CREATE USER user1 WITH PASSWORD 'password';
GRANT ALL PRIVILEGES ON DATABASE "CARS" to user1;

CREATE TABLE CAR(
   CAR_ID             INT PRIMARY KEY   NOT NULL,
   MANUFACTURER_ID    INT    NOT NULL,
   MODEL_NAME         VARCHAR(50),
   WEIGHT             VARCHAR(50),
   PRICE         	  INT,
   SALESPERSON_ID     INT    NOT NULL
);

CREATE TABLE SALES(
   SALE_ID            INT PRIMARY KEY   NOT NULL,
   SALE_DATE          TIMESTAMP, 
   CAR_ID		      INT    NOT NULL,
   SERIAL_NUMBER      INT  NOT NULL,
   CUSTOMER_ID        INT  NOT NULL,
   SALESPERSON_ID     INT  NOT NULL,
   QUANTITY           INT,
   PRICE			  INT,
   AMOUNT			  INT
);

CREATE TABLE SALESPERSON(
   SALESPERSON_ID             INT PRIMARY KEY   NOT NULL,
   SALESPERSON_NAME         VARCHAR(50)
);

CREATE TABLE MANUFACTURER(
   MANUFACTURER_ID             INT PRIMARY KEY   NOT NULL,
   MANUFACTURER_NAME         VARCHAR(50)
);

CREATE TABLE CUSTOMER(
   CUSTOMER_ID           INT PRIMARY KEY     NOT NULL,
   CUSTOMER_NAME         VARCHAR(50),
   CUSTOMER_PHONE         	  INT
);





