#task.sql script to execute tasked sql

#First query sql code
SELECT CS.CUSTOMER_ID,CS.CUSTOMER_NAME,SUM(SA.AMOUNT) SPENDING FROM CUSTOMER CS,SALES SA
WHERE CS.CUSTOMER_ID =SA.CUSTOMER_ID GROUP BY CS.CUSTOMER_ID,CS.CUSTOMER_NAME;

#second query sql code
WITH MTH_SALES
AS  
    (SELECT MA.MANUFACURED_ID, MA.MANUFACTURER_NAME, SA.SALE_ID, SA.QUANTITY,
           ROW_NUMBER(ORDER BY SQ.QUANTITY DESC) SALE_RANK
    FROM SALES SA JOIN CARS CA ON CA.CARS_ID = SA.CARS_ID
    JOIN MANUFACTURER MA ON MA.MANUFACTURER_ID = CA.MANUFACTURER_ID
    WHERE SA.SALE_DATE BETWEEN TRUNC(CURRENT_DATE, 'MM') AND CURRENT_DATE)
SELECT MANUFACURED_ID,  MANUFACTURER_NAME, QUANTITY FROM MTH_SALES
WHERE SALE_RANK <= 3
ORDER BY SALE_RANK DESC;